# Generated by Django 4.1.7 on 2023-06-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="user", old_name="bio", new_name="comment",),
    ]
